export const legalChecklist = [
  { id: "will-sm", label: "Service Member's will is in good standing" },
  { id: "will-spouse", label: "Spouse's will is in good standing" },
  { id: "living-will", label: "Create a living will or trust, if desired" },
  {
    id: "medical-directive",
    label: "Check with healthcare provider about Advanced Directive type for your state",
  },
  { id: "medical-poa", label: "Assign medical power of attorney (POA)" },
  {
    id: "guardian",
    label: "Assign a guardian for children (Power of Attorney for Care of Children)",
  },
  { id: "financial-poa", label: "Verify POA requirements with all financial institutions" },
  {
    id: "poa-storage",
    label: "Store POA documentation in safe, accessible location with designated person",
  },
  { id: "life-insurance", label: "Confirm life insurance plans are current" },
  { id: "beneficiaries", label: "Confirm life insurance beneficiaries are current" },
  {
    id: "id-cards",
    label: "ID cards for all family members secured (driver's licenses and military ID cards)",
  },
  { id: "birth-certs", label: "Birth certificates of all family members" },
  { id: "marriage-license", label: "Marriage license" },
  { id: "ss-cards", label: "Social Security cards for all immediate family members" },
  { id: "vehicle-titles", label: "Car and vehicle titles (boat, truck, trailer)" },
  { id: "passports", label: "Passports valid throughout the deployment" },
  { id: "tax-returns", label: "Past 5 years of tax returns" },
  { id: "passwords", label: "Account passwords and security question answers documented" },
]

export const financialChecklist = [
  { id: "direct-deposit", label: "Arrange direct deposit of pay and allotments to checking or savings" },
  { id: "spouse-access", label: "Confirm spouse has access to needed accounts during deployment" },
  { id: "mypay", label: "Familiarize family with how to view myPay for deposit verification" },
  { id: "account-manager", label: "Establish who will manage financial accounts at home" },
  { id: "mortgage", label: "Set up automatic payment for mortgage or rental payments" },
  {
    id: "utilities",
    label: "Set up automatic payment for household bills (water, electric, cable, Internet)",
  },
  { id: "cell-phone", label: "Set up automatic payment for cell phone bill" },
  { id: "insurance", label: "Set up automatic payment for house/rental/property insurance" },
  { id: "credit-cards", label: "Set up automatic payment for credit card bills" },
  {
    id: "loans",
    label: "Set up automatic payment for loans (consider consolidating before deployment)",
  },
  { id: "childcare", label: "Arrange child care payment setup" },
  { id: "storage", label: "Arrange storage unit payment if applicable" },
  { id: "car-payments", label: "Set up automatic car payments" },
  { id: "les-access", label: "Ensure LES access for family if questions arise about paychecks" },
  { id: "credit-usage", label: "Discuss credit card usage plan with family during deployment" },
  { id: "cc-notify", label: "Notify credit card companies about overseas card usage" },
  { id: "cc-expiration", label: "Verify credit cards won't expire during deployment" },
  { id: "cc-list", label: "Create list of all credit card numbers and company phone numbers" },
  { id: "savings-plan", label: "Evaluate if savings plan should be adjusted during deployment" },
  { id: "safe-deposit", label: "Share access to safe deposit boxes with family members" },
  { id: "taxes", label: "Arrange for tax returns or extensions if due during deployment" },
  {
    id: "periodic-expenses",
    label: "Make arrangements for periodic expenses (auto insurance, property taxes)",
  },
  {
    id: "banking-info",
    label: "Share banking/computer info: usernames, passwords, PINs, security questions",
  },
  { id: "financial-assistance", label: "Ensure family knows where to get financial assistance if needed" },
]

export const homeChecklist = [
  { id: "home-insurance", label: "Renter's/homeowner's insurance is current" },
  { id: "maintenance", label: "Household routine maintenance is current" },
  { id: "lease-renewal", label: "If renting, arrange for lease renewal if needed during deployment" },
  { id: "lawn-care", label: "Have a lawn care plan in place" },
  {
    id: "firearms",
    label: "Firearms properly locked and stored, inaccessible to unauthorized persons",
  },
  { id: "car-insurance", label: "Car and vehicle insurance is current" },
  { id: "registrations", label: "All vehicle registrations are current and accessible" },
  { id: "vehicle-titles-access", label: "Vehicle titles are accessible and in good standing" },
  { id: "base-stickers", label: "Base stickers are current" },
  { id: "inspection-stickers", label: "Inspection stickers are current" },
  { id: "vehicle-maintenance", label: "Routine vehicle maintenance is up to date" },
  { id: "extra-keys", label: "Extra sets of car keys are on hand" },
  { id: "roadside", label: "Roadside assistance available for vehicles in use during deployment" },
  { id: "emergency-kit", label: "Emergency kit in each car" },
  { id: "unused-vehicles", label: "Arrangements made to maintain vehicles not in use during deployment" },
  {
    id: "stored-vehicle",
    label: "If storing vehicle, remove personal items and check on insurance rates",
  },
]

export const familyChecklist = [
  { id: "family-care-plan", label: "Complete Family Care Plan and submit to Commanding Officer" },
  { id: "inform-extended", label: "Inform extended family members and friends of upcoming deployment" },
  { id: "support-network", label: "Explore how family and friends can provide support during deployment" },
  { id: "connect-families", label: "Connect with similar families and schedule regular check-ins" },
  { id: "tdy-orders", label: "Maintain copies of TDY orders at home" },
  { id: "health-records", label: "Maintain immunization and health records at home for children" },
  { id: "spare-key", label: "Provide spare house key to trusted neighbor" },
  { id: "cdc-register", label: "Register children with local Child Development Center if near base" },
  { id: "ids-valid", label: "Ensure military IDs and driver's licenses won't expire during deployment" },
  { id: "transportation", label: "Arrange transportation options if family members don't drive" },
  { id: "pets", label: "Arrange transportation/care for pets if staying with others during deployment" },
  { id: "command-contact", label: "Document command contact information" },
  { id: "tricare", label: "Confirm access to TRICARE Health Plan and TRICARE Dental" },
  { id: "pcm", label: "Document names of PCM, doctors, and healthcare professionals" },
  { id: "emergency-data", label: "Update Emergency Data (yearly) and share copy with family" },
  {
    id: "emergency-contacts",
    label: "Create list of emergency contacts for both deploying and home family",
  },
  { id: "communication-plan", label: "Clarify how and when you will keep in touch (calls, video, email)" },
  { id: "internet-phone", label: "Confirm Internet and phone capabilities while deployed" },
  { id: "communication-barriers", label: "Explore barriers to communication (time zones, security)" },
  { id: "packages", label: "Clarify if packages can be sent/received and share shipping address" },
  { id: "unmarried-contact", label: "If unmarried, inform parents how to contact command" },
  { id: "children-communication", label: "Discuss with children about staying in touch with deployed parent" },
  { id: "emergency-communication", label: "Clarify emergency communication plan and what qualifies" },
  { id: "routine-changes", label: "Discuss family routine changes needed during deployment" },
  { id: "what-stays-same", label: "Discuss what should remain the same for family" },
  {
    id: "important-dates",
    label: "Explore important dates the deploying member will miss and plan accordingly",
  },
  { id: "resources", label: "Become familiar with resources (FOCUS Project, United Through Reading)" },
  { id: "reintegration", label: "Discuss plans and expectations for homecoming and reintegration" },
]